/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OurWorksRouteImport } from './routes/our-works'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFileIdRouteImport } from './routes/api/file.$id'

const OurWorksRoute = OurWorksRouteImport.update({
  id: '/our-works',
  path: '/our-works',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileIdRoute = ApiFileIdRouteImport.update({
  id: '/api/file/$id',
  path: '/api/file/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/author': typeof AuthorRoute
  '/editor': typeof EditorRoute
  '/our-works': typeof OurWorksRoute
  '/api/file/$id': typeof ApiFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/author': typeof AuthorRoute
  '/editor': typeof EditorRoute
  '/our-works': typeof OurWorksRoute
  '/api/file/$id': typeof ApiFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/author': typeof AuthorRoute
  '/editor': typeof EditorRoute
  '/our-works': typeof OurWorksRoute
  '/api/file/$id': typeof ApiFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/author' | '/editor' | '/our-works' | '/api/file/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/author' | '/editor' | '/our-works' | '/api/file/$id'
  id: '__root__' | '/' | '/author' | '/editor' | '/our-works' | '/api/file/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorRoute: typeof AuthorRoute
  EditorRoute: typeof EditorRoute
  OurWorksRoute: typeof OurWorksRoute
  ApiFileIdRoute: typeof ApiFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/our-works': {
      id: '/our-works'
      path: '/our-works'
      fullPath: '/our-works'
      preLoaderRoute: typeof OurWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file/$id': {
      id: '/api/file/$id'
      path: '/api/file/$id'
      fullPath: '/api/file/$id'
      preLoaderRoute: typeof ApiFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorRoute: AuthorRoute,
  EditorRoute: EditorRoute,
  OurWorksRoute: OurWorksRoute,
  ApiFileIdRoute: ApiFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
